# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Furyctl < Formula
  desc "furyctl binary"
  homepage "https://gihub.com/sighupio/furyctl"
  version "0.25.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/sighupio/furyctl/releases/download/v0.25.1/furyctl-darwin-arm64.tar.gz"
      sha256 "4eb6895b5b3f9bd8b0e2146fe7bdf535607968169a9a81f2ba58bd6c664f53d0"

      def install
        bin.install 'furyctl'
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/sighupio/furyctl/releases/download/v0.25.1/furyctl-darwin-amd64.tar.gz"
      sha256 "c05293fe69e6974b48c7f5b503a51c5c452028959231f2cee7d414afee4ddf01"

      def install
        bin.install 'furyctl'
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sighupio/furyctl/releases/download/v0.25.1/furyctl-linux-arm64.tar.gz"
      sha256 "c5b3382e3052914228820ef901a7d499e1dcb4d04b68ab10a4db5f5821f3a1c3"

      def install
        bin.install 'furyctl'
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/sighupio/furyctl/releases/download/v0.25.1/furyctl-linux-amd64.tar.gz"
      sha256 "3a0c480897c81307dddbcd9a0637813c0015166d9617e3856c88c351a70d6ca9"

      def install
        bin.install 'furyctl'
      end
    end
  end

  conflicts_with "furyctl"

  test do
    system "#{bin}/furyctl"
  end
end
